"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['tmux_history', 'fmt_query', 'main']

# %% ../nbs/00_core.ipynb 2
from fastcore.script import *
from fastcore.tools import *
from fastcore.utils import *
from lisette import *

# %% ../nbs/00_core.ipynb 13
def tmux_history():
    o = shell('tmux capture-pane -p', capture_output=True, text=True)
    return o.stdout or o.stderr
    

# %% ../nbs/00_core.ipynb 15
def fmt_query(query):
    q = f"""
<tmux_history>
{tmux_history()}
</tmux_history>
<user_query>
{query}
</user_query>"""
    return q

# %% ../nbs/00_core.ipynb 19
@call_parse
def main(query:str): # Question to ask the assistant
  'Bash buddy assitant for your terminal.'
  c = Chat('claude-sonnet-4-5-20250929', tools=[view,rg])
  res = c(fmt_query(query), max_steps=5)
  print(res.choices[0].message.content)    
